-- 코드를 입력하세요
WITH RECURSIVE hours AS (
    SELECT 0 AS h
    UNION ALL
    SELECT h + 1 FROM hours WHERE h < 23
)
SELECT h AS HOUR,
       COUNT(A.DATETIME) AS COUNT
FROM hours
LEFT JOIN ANIMAL_OUTS A
ON HOUR(A.DATETIME) = h
GROUP BY h
ORDER BY h;